### ISSUE TITLE
Where to find the push-button?

### ISSUE THREAD

**Issue by atoav** [BleepSound/rp2040-chord-vco#1]
I have a hard time sourcing the right switch for `MEC Low Profile single pole normally-open illuminated tactile switch`. Is there an actual manufacturer part number (MPN) I could look for?

**Comment by comejar** [comment]
CANNOT CONFIRM THIS YET

But googling the part number in BOM shows a datasheet from thonk and looking on their site this is the button that matches that datasheet and part number 

https://www.thonk.co.uk/shop/low-profile-led-buttons/

again i cannot confirm this is right for anyone who sees this, will update when i build this module to let you know for sure

**Comment by atoav** [comment]
I have the high profile version of that switch and can verify that it works. The LED on that switch is bicolor, which means the way you put it in decides the color. Because the supply voltage for that switch is negative, the color of the leg pointing *down* will be the color in which it glows.

Because the LED serves no purpose other than lighting the button itself, there is another, more common button that should work (pictured right):  

![switches](https://github.com/BleepSound/rp2040-chord-vco/assets/6620266/193705b2-c13e-44ef-b3dd-19289db442d7)  

I confirmed with the continuity check of the multimeter that these two are switching the same pins through, so you don't get the LED, but if you don't need that you can also take that switch.

**Comment by arthursaunier** [comment]
Can confirm it's the one from Thonk originally @comejar. It's the only place I found those types of buttons. Any other button like the one proposed by @atoav should work !
