### ISSUE TITLE
What is the status of this module? tested?

### ISSUE THREAD

**Issue by comejar** [BleepSound/rp2040-chord-vco#2]
Was wondering you this has been built and tested before or if it is just in untested state still

Unlike your other github this one doesnt have the markings for where a module currently is at

**Comment by atoav** [comment]
I just built one and it produces sounds and all he knobs/switches/buttons perform their functions. What I did not test yet, is the CV inputs, but given the simple nature of the circuit it would surprise me if it didn't work.

**Comment by comejar** [comment]
> I just built one and it produces sounds and all he knobs/switches/buttons perform their functions. What I did not test yet, is the CV inputs, but given the simple nature of the circuit it would surprise me if it didn't work.

Great to hear thanks a lot for the response, hopefully the cv works too !

**Comment by arthursaunier** [comment]
Hey guys, sorry was a bit out of it for the past few months. 

Yes this module works and is tested !

I updated the documentation to show that on the website.

cheers
