### ISSUE TITLE
Warbling noise

### ISSUE THREAD

**Issue by Pabcandy** [BleepSound/rp2040-chord-vco#3]
Hi, I built this today but get a strange warbling tone on all settings similar to excessive pwm or fm. On initial press of the button I get what I is how it should sound for about a second before it warbles. Tried re flashing the software so it might be a build error but I can’t see any problems with the hardware. Any ideas on where I might have gone wrong?
I can put a link to a video if that helps?
Thank you very much for putting this out there, it really is appreciated.
Phil

**Comment by Pabcandy** [comment]
HI,
I reverted to v1.1 and the issue resolved - I thought it was a software issue as when the button is first pressed the sound is pure for about a second - so it must be the debounce. 
Thanks

**Comment by arthursaunier** [comment]
Hello Phil! 
Sorry I was not very active this past few months on github.
I checked on my side and as you said it's a soft issue. I'm gonna update the repo right away. 
Cheers!
